"add the task of smoke emission preprocessing" (#441)

diff --git a/jobs/JREGIONAL_PROCESS_SMOKE b/jobs/JREGIONAL_PROCESS_SMOKE
--- a/jobs/JREGIONAL_PROCESS_SMOKE
+++ b/jobs/JREGIONAL_PROCESS_SMOKE
@@ -1,15 +1,11 @@
 #!/bin/bash
-
 #
 #-----------------------------------------------------------------------
 #
-# This script copies files from various directories into the experiment
-# directory, creates links to some of them, and modifies others (e.g. 
-# templates) to customize them for the current experiment setup.
+# This J-JOB script runs the radar reflectivity preprocess 
+#      for the FV3-LAM model
 #
 #-----------------------------------------------------------------------
-#
-
 #
 #-----------------------------------------------------------------------
 #
@@ -19,6 +15,7 @@
 #
 . ${GLOBAL_VAR_DEFNS_FP}
 . $USHDIR/source_util_funcs.sh
+
 #
 #-----------------------------------------------------------------------
 #
@@ -37,6 +34,7 @@
 #
 #-----------------------------------------------------------------------
 #
+
 scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
 scrfunc_fn=$( basename "${scrfunc_fp}" )
 scrfunc_dir=$( dirname "${scrfunc_fp}" )
@@ -52,37 +50,38 @@ print_info_msg "
 Entering script:  \"${scrfunc_fn}\"
 In directory:     \"${scrfunc_dir}\"
 
-This is the J-job script for the task that runs a forecast with FV3 for 
-the specified cycle.
+This is the J-job script for the task that runs a radar reflectivity 
+preprocess with FV3 for the specified cycle.
 ========================================================================"
 #
 #-----------------------------------------------------------------------
 #
-# Create the INPUT and RESTART directories under the run directory.
+# Create the working directory under the cycle directory.
 #
 #-----------------------------------------------------------------------
-# CYCLE_TYPE is to indicate which type of cycle this job for:
-#   spinup: this job is for spin-up cycles
-#   others(prod): this job is for product cycle
 #
-CYCLE_TYPE=${CYCLE_TYPE:-prod}
 if [ ${CYCLE_TYPE} == "spinup" ]; then
-  run_dir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam_spinup"
-elif  [ ${CYCLE_TYPE} == "ensinit" ]; then
-  run_dir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam_ensinit"
-elif  [ ${CYCLE_TYPE} == "ensfcst" ]; then
-  run_dir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam_long"
+  workdir=${CYCLE_DIR}/process_smoke_spinup
 else
-  run_dir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam"
+  workdir=${CYCLE_DIR}/process_smoke
 fi
-mkdir_vrfy -p ${run_dir}/INPUT
-mkdir_vrfy -p ${run_dir}/RESTART
+rm -fr ${workdir}
+mkdir_vrfy -p ${workdir}
 #
 #
 #
 gridspec_dir=${NWGES_BASEDIR}/grid_spec
-mkdir_vrfy -p ${gridspec_dir}
 #
+#-----------------------------------------------------------------------
+#
+# Set the name of and create the directory in which the output from this
+# script will be saved for long time (if that directory doesn't already exist).
+# Usually ics_dir under tmpnwprd should be purged fairly soon after cycle done
+#
+#-----------------------------------------------------------------------
+#
+rave_nwges_dir=${NWGES_DIR}/RAVE_INTP
+mkdir_vrfy -p "${rave_nwges_dir}"
 #-----------------------------------------------------------------------
 #
 # Call the ex-script for this J-job and pass to it the necessary varia-
@@ -90,16 +89,63 @@ mkdir_vrfy -p ${gridspec_dir}
 #
 #-----------------------------------------------------------------------
 #
-$SCRIPTSDIR/exregional_run_fcst.sh \
-  cdate="${CDATE}" \
-  cycle_type="${CYCLE_TYPE}" \
-  cycle_dir="${run_dir}" \
-  gridspec_dir="${gridspec_dir}" \
-  ensmem_indx="${ENSMEM_INDX}" \
-  slash_ensmem_subdir="${SLASH_ENSMEM_SUBDIR}" \
-  NWGES_BASEDIR="${NWGES_BASEDIR}" || \
+cd_vrfy ${workdir}
+python -u ${SCRIPTSDIR}/preprocess_smoke.py \
+  "${FIRE_RRFS_ROOT}/${PREDEF_GRID_NAME}/fixed" \
+  "${FIRE_RAVE_DIR}" \
+  "${rave_nwges_dir}" \
+  "${PREDEF_GRID_NAME}" \
 print_err_msg_exit "\
-Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
+Call to pyscript \"${scrfunc_fn}\" failed."
+
+ECHO=/bin/echo
+AWK="/bin/gawk --posix"
+SED=/bin/sed
+DATE=/bin/date
+
+START_DATE=$(echo "${CDATE}" | sed 's/\([[:digit:]]\{2\}\)$/ \1/')
+YYYYMMDDHH=$(date +%Y%m%d%H -d "${START_DATE}")
+YYYYMMDD=${YYYYMMDDHH:0:8}
+HH=${YYYYMMDDHH:8:2}
+echo ${YYYYMMDD}
+echo ${HH}
+
+current_day=`${DATE} -d "${YYYYMMDD}"`
+HH=${HH}
+current_hh=`${DATE} -d ${HH} +"%H"`
+prev_hh=`${DATE} -d "$current_hh -24 hour" +"%H"`
+previous_day=`${DATE} '+%C%y%m%d' -d "$current_day-1 days"`
+previous_day=${previous_day}${prev_hh}
+output_filename=SMOKE_RRFS_data_${YYYYMMDDHH}00.nc
+#output_filename=SMOKE_RRFS_data_${previous_day}00.nc
+echo ${previous_day}
+echo ${output_filename}
+
+#cd_vrfy /mnt/lfs4/BMC/gsd-fv3-dev/FIRE_RRFS_ROOT/RAVE_INTP2
+cd_vrfy ${rave_nwges_dir}
+echo ${rave_nwges_dir}
+
+# Convert START_TIME from 'YYYYMMDDHH' format to Unix date format, e.g. "Fri May  6 19:50:23 GMT 2005"
+if [ `${ECHO} "${previous_day}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+  previous_day=`${ECHO} "${previous_day}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+else
+  ${ECHO} "ERROR: start time, '${previous_day}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+  exit 1
+fi
+previous_day=`${DATE} -d "${previous_day}"`
+echo ${previous_day}
+
+nfiles=24
+files2cat=()
+for i in $(seq 0 $(($nfiles - 1)) )
+do
+timestr=`date +%Y%m%d%H -d "$previous_day + $i hours"`
+echo ${timestr}
+files2cat[$i]=${PREDEF_GRID_NAME}_intp_${timestr}00_${timestr}00.nc
+done
+echo ${files2cat[*]}
+ncrcat ${files2cat[*]} ${output_filename} 
+
 #
 #-----------------------------------------------------------------------
 #
